services:
  spring:
    # image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    build: .
    ports:
      - "8080:8080"
    container_name: "klkl-server"
    env_file:
      - .env
    depends_on:
      klkl_db:
        condition: service_healthy
    restart: always
    networks:
      - klkl-net

  klkl_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: "klkl-db"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - klkl-net

networks:
  klkl-net:
    driver: bridge

volumes:
  mysql-data:
